apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-1
spec:
  selector:
    matchLabels:
      app: node-1
  template:
    metadata:
      labels:
        app: node-1
    spec:
      containers:
        - name: kafka
          image: node-1:dev
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-env