#!/bin/bash

handle_command() {
  if [[ $1 == "start" ]]; then
    start_build "$2"
  fi
}

start_build() {
  local tag=$1
    echo -e "[\e[33mWAIT\e[39m] Building images tag $tag"
    docker build -t coreografia_microservicos/master:$tag master/.
    docker build -t coreografia_microservicos/node-1:$tag node-1/.
    docker build -t coreografia_microservicos/node-2:$tag node-2/.
    docker build -t coreografia_microservicos/postgres:$tag postgres/.

    echo -e "[\e[33mWAIT\e[39m] Push images tag $tag"
    docker push coreografia_microservicos/master:$tag
    docker push coreografia_microservicos/node-1:$tag
    docker push coreografia_microservicos/node-2:$tag
    docker push coreografia_microservicos/postgres:$tag

    echo -e "[\e[33mWAIT\e[39m] Successfully $tag"
  exit
}

handle_command "$1" "$2"
