apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:6.0.0
          ports:
            - containerPort: 9092
            - containerPort: 9094
          envFrom:
            - configMapRef:
                name: app-env