apiVersion: v1
kind: Service

metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  type: ClusterIP
  ports:
    - name: kafka-service
      port: 9092
      targetPort: 9092
      protocol: TCP
