apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
spec:
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-enterprise-control-center:6.0.0
          ports:
            - containerPort: 9021
          envFrom:
            - configMapRef:
                name: app-env