apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command: ['sh', '-c', 'until nc -z kafka-service 9092; do echo waiting for kafka; sleep 2; done;']
      containers:
        - name: kafka
          image: mazepa/coreografia-microservicos:master
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-env
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always