apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: kafka
          image: mazepa/coreografia-microservicos:master
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-env