apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-2
spec:
  selector:
    matchLabels:
      app: node-2
  template:
    metadata:
      labels:
        app: node-2
    spec:
      containers:
        - name: kafka
          image: mazepa/coreografia-microservicos:node-2
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-env