apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: mazepa/coreografia-microservicos:postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: app-env